language: r

env:
   global:
     - R_BUILD_ARGS="--no-manual"
     - R_CHECK_ARGS="--as-cran --no-manual"

r_github_packages:
 - jimhester/robustr
 - jimhester/covr
 - jeroenooms/curl

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
 slack: ropensci:wh30e1MP9Am3wXb2wJx1ZRFi:builds
 email:
   on_success: change
   on_failure: change
